from __future__ import annotations

import decimal

decimal.getcontext().prec = 28
decimal.getcontext().rounding = decimal.ROUND_HALF_EVEN

D = decimal.Decimal
ZERO = D("0")
ONE = D("1")
HUNDRED = D("100")

INITIAL_CAPITAL_CNY = D("1000000")

DEFAULT_SPREAD_BPS = D("0.004")
DEFAULT_EXCHANGE_FEE_MIN_BPS = D("0.001")
DEFAULT_EXCHANGE_FEE_MAX_BPS = D("0.004")

A_STOCK_COMMISSION_BPS = D("0.0003")
A_STOCK_COMMISSION_MIN = D("5")
A_STOCK_STAMP_TAX_BPS = D("0.001")
US_STOCK_COMMISSION_BPS = D("0.005")
CRYPTO_TAKER_FEE_BPS = D("0.001")
CRYPTO_MAKER_FEE_BPS = D("0.001")

DEFAULT_SLIPPAGE_BPS = D("0.0005")

DEFAULT_DAILY_INTEREST_RATE = D("0.0005")
DEFAULT_MAX_LOAN_RATIO = D("0.5")
DEFAULT_COLLATERAL_WARNING_RATIO = D("1.2")
DEFAULT_COLLATERAL_LIQUIDATION_RATIO = D("1.1")

A_STOCK_LOT_SIZE = 100
US_STOCK_MIN_QUANTITY = 1
CRYPTO_QUANTITY_PRECISION = 4

DECIMAL_PRECISION = 8

SNAPSHOT_INTERVAL_SECONDS = 3600
STATE_CHECK_INTERVAL_SECONDS = 600

AI_DECISION_TIMEOUT_SECONDS = 30
MAX_CONCURRENT_AI_COUNT = 10
DECISION_CYCLE_TIMEOUT_SECONDS = 30

DATA_FETCH_TIMEOUT_SECONDS = 10
CACHE_TTL_REALTIME_SECONDS = 60
RATE_LIMIT_INITIAL_DELAY_SECONDS = D("1")
RATE_LIMIT_MAX_DELAY_SECONDS = D("60")
RATE_LIMIT_BACKOFF_FACTOR = 2
RATE_LIMIT_MAX_RETRIES = 10

CONTEXT_MAX_TOKENS = 4096
CONTEXT_PRIORITY_MARKET_STATE = 4
CONTEXT_PRIORITY_RECENT_TRADES = 3
CONTEXT_PRIORITY_HISTORICAL_SUMMARY = 2
CONTEXT_PRIORITY_AUXILIARY = 1

BACKTEST_MIN_SPEED_MULTIPLIER = 100

GUI_REFRESH_INTERVAL_MS = 5000
GUI_RESPONSE_TIMEOUT_MS = 200
SNAPSHOT_WRITE_TIMEOUT_SECONDS = 5

COVERAGE_THRESHOLD = 80
